# Generated by Django 2.2.7 on 2020-01-07 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airmap', '0004_auto_20200107_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='poo',
            new_name='geom',
        ),
    ]
