# Generated by Django 2.2.7 on 2020-01-16 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airmap', '0006_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 13, 26, 2, 957421)),
        ),
    ]
