# Generated by Django 2.2.7 on 2020-01-16 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('airmap', '0009_auto_20200116_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
