# Generated by Django 2.2.7 on 2020-01-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airmap', '0010_auto_20200116_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='longitude',
        ),
    ]
