# Generated by Django 2.2.7 on 2020-02-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airmap', '0011_auto_20200116_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='mac_address',
            field=models.CharField(default='00:00:00:00:00:00', max_length=18),
            preserve_default=False,
        ),
    ]
