# Generated by Django 2.2.7 on 2020-03-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airmap', '0012_monitor_mac_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
